
spring:
  ##数据库连接信息
  datasource:
    url: jdbc:mysql://118.31.120.113:3306/myblog?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&charset=utf8
    username: yuzhou
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    ###################以下为druid增加的配置###########################
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中


mybatis:
  mapper-locations: classpath*:sql/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

