CREATE TABLE `ARTICAL_INFO` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `ARTICAL_CONTENT` longblob NOT NULL,
  `CTRATE_AT` datetime NOT NULL,
  `CREATE_BY` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs NOT NULL,
  `UPDATE_AT` datetime NOT NULL,
  `UPDATE_BY` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `ARTICAL_FK` FOREIGN KEY (`ID`) REFERENCES `USER_INFO` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs