CREATE TABLE `ARTICAL_INFO` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `ARTICAL_CONTENT` longblob NOT NULL,
  `CTRATED_AT` datetime NOT NULL,
  `CREATED_BY` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs NOT NULL,
  `UPDATED_AT` datetime NOT NULL,
  `UPDATED_BY` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs NOT NULL,
  `ARTICAL_TITLE` varchar(256) COLLATE utf8mb4_0900_as_cs NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `USER_INFO_ID` FOREIGN KEY (`ID`) REFERENCES `USER_INFO` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs